apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sock-user-db
  namespace: test
spec:
  type: git
  params:
    - name: revision
      value: test
    - name: url
      value: https://github.com/ManarAbdulrahman/level-3-project.git
